my_memo_app/models.py
from flask_sqlalchemy import SQLAlchemy
# ▼▼▼ リスト 11-1の追加 ▼▼▼
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
# ▲▲▲ リスト 11-1の追加 ▲▲▲

# Flask-SQLAlchemyの生成
db = SQLAlchemy()

# ==================================================
# モデル
# ==================================================
# メモ
class Memo(db.Model):
    # テーブル名
    __tablename__ = 'memos'
    # ID（PK）
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # タイトル（NULL許可しない）
    title = db.Column(db.String(50), nullable=False)
    # 内容
    content = db.Column(db.Text)

# ▼▼▼ リスト 11-1の追加 ▼▼▼
# ユーザー
class User(UserMixin, db.Model):
    # テーブル名
    __tablename__ = 'users'
    # ID（PK）    
    id = db.Column(db.Integer, primary_key=True)
    # ユーザー名
    username = db.Column(db.String(50), unique=True, nullable=False)
    # パスワード
    password = db.Column(db.String(120), nullable=False)
    # パスワードをハッシュ化して設定する
    def set_password(self, password):
        self.password = generate_password_hash(password)
    # 入力したパスワードとハッシュ化されたパスワードの比較
    def check_password(self, password):
        return check_password_hash(self.password, password)
# ▲▲▲ リスト 11-1の追加 ▲▲▲

my_memo_app/forms.py
# ▼▼▼ リスト 11-2の修正 ▼▼▼
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError
from models import Memo, User
# ▲▲▲ リスト 11-2の修正 ▲▲▲

# ==================================================
# Formクラス
# ==================================================
# メモ用入力クラス
class MemoForm(FlaskForm):
    # タイトル
    title = StringField('タイトル：', validators=[DataRequired('タイトルは必須入力です'), 
                            Length(max=10, message='10文字以下で入力してください')])
    # 内容
    content = TextAreaField('内容：')
    # ボタン
    submit = SubmitField('送信')

    # カスタムバリデータ
    def validate_title(self, title):
        # StringFieldオブジェクトではなく、その中のデータ（文字列）をクエリに渡す必要があるため
        # 以下のようにtitle.dataを使用して、StringFieldから実際の文字列データを取得する
        memo = Memo.query.filter_by(title=title.data).first()
        if memo:
            raise ValidationError(f"タイトル '{title.data}' は既に存在します。\
                                  別のタイトルを入力してください。")

# ▼▼▼ リスト 11-2の追加 ▼▼▼
# ログイン用入力クラス
class LoginForm(FlaskForm):
    username = StringField('ユーザー名：', 
                           validators=[DataRequired('ユーザー名は必須入力です')])
    # パスワード：パスワード入力
    password = PasswordField('パスワード: ',
                             validators=[Length(4, 10,
                                    'パスワードの長さは4文字以上10文字以内です')])
    # ボタン
    submit = SubmitField('ログイン')
    
    # カスタムバリデータ
    # 英数字と記号が含まれているかチェックする
    def validate_password(self, password):
        if not (any(c.isalpha() for c in password.data) and \
            any(c.isdigit() for c in password.data) and \
            any(c in '!@#$%^&*()' for c in password.data)):
            raise ValidationError('パスワードには【英数字と記号：!@#$%^&*()】を含める必要があります')

# サインアップ用入力クラス
class SignUpForm(LoginForm):
    # ボタン
    submit = SubmitField('サインアップ')

    # カスタムバリデータ
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('そのユーザー名は既に使用されています')
# ▲▲▲ リスト 11-2の追加 ▲▲▲

my_memo_app/app.py
from flask import Flask
from flask_migrate import Migrate
from models import db, User
from flask_login import LoginManager
# ▼▼▼ リスト 12-11の追加 ▼▼▼
from auth.views import auth_bp
from memo.views import memo_bp
# ▲▲▲ リスト 12-11の追加 ▲▲▲

# ==================================================
# Flask
# ==================================================
app = Flask(__name__)
# 設定ファイル読み込み
app.config.from_object("config.Config")
# dbとFlaskとの紐づけ
db.init_app(app)
# マイグレーションとの紐づけ（Flaskとdb）
migrate = Migrate(app, db)
# LoginManagerインスタンス
login_manager = LoginManager()
# LoginManagerとFlaskとの紐づけ
login_manager.init_app(app)
# ログインが必要なページにアクセスしようとしたときに表示されるメッセージを変更
login_manager.login_message = "認証していません：ログインしてください"
# ▼▼▼ リスト 12-11の修正 ▼▼▼
# 未認証のユーザーがアクセスしようとした際に
# リダイレクトされる関数名を設定する(ブループリント対応)
login_manager.login_view = 'auth.login'
# blueprintをアプリケーションに登録
app.register_blueprint(auth_bp)
app.register_blueprint(memo_bp)
# ▲▲▲ リスト 12-11の修正 ▲▲▲

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# viewsのインポート
from views import *

# ==================================================
# 実行
# ==================================================
if __name__ == "__main__":
    app.run()

my_memo_app/memo/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models import db, Memo
from forms import MemoForm
from flask_login import login_required

# memoのBlueprint
memo_bp = Blueprint('memo', __name__, url_prefix='/memo')

# ==================================================
# ルーティング
# ==================================================
# 一覧
@memo_bp.route("/")
@login_required
def index():
    # メモ全件取得
    memos = Memo.query.all()
    # 画面遷移
    return render_template("memo/index.html", memos=memos)

# 登録（Form使用）
@memo_bp.route("/create", methods=["GET", "POST"])
@login_required
def create():
    # Formインスタンス生成
    form = MemoForm()
    if form.validate_on_submit():
        # データ入力取得
        title = form.title.data
        content = form.content.data
        # 登録処理
        memo = Memo(title=title, content=content)
        db.session.add(memo)
        db.session.commit()
        # フラッシュメッセージ
        flash("登録しました")          
        # 画面遷移
        return redirect(url_for("memo.index"))
    # GET時
    # 画面遷移
    return render_template("memo/create_form.html", form=form)

# 更新（Form使用）
@memo_bp.route("/update/<int:memo_id>", methods=["GET", "POST"])
@login_required
def update(memo_id):
    # データベースからmemo_idに一致するメモを取得し、
    # 見つからない場合は404エラーを表示
    target_data = Memo.query.get_or_404(memo_id)
    # Formに入れ替え
    form = MemoForm(obj=target_data)
    
    if request.method == 'POST' and form.validate():
        # 変更処理
        target_data.title = form.title.data
        target_data.content = form.content.data
        db.session.merge(target_data)
        db.session.commit()
        # フラッシュメッセージ
        flash("変更しました")        
        # 画面遷移
        return redirect(url_for("memo.index"))
    # GET時
    # 画面遷移
    return render_template("memo/update_form.html", form=form, edit_id = target_data.id)

# 削除
@memo_bp.route("/delete/<int:memo_id>")
@login_required
def delete(memo_id):
    # データベースからmemo_idに一致するメモを取得し、
    # 見つからない場合は404エラーを表示
    memo = Memo.query.get_or_404(memo_id)
    # 削除処理
    db.session.delete(memo)
    db.session.commit()
    # フラッシュメッセージ
    flash("削除しました")
    # 画面遷移
    return redirect(url_for("memo.index"))

my_memo_app/views.py
from flask import render_template
from app import app

# ==================================================
# ルーティング
# ==================================================
# モジュールのインポート
from werkzeug.exceptions import NotFound

# エラーハンドリング
@app.errorhandler(NotFound)
def show_404_page(error):
    msg = error.description
    print('エラー内容：',msg)
    return render_template('errors/404.html', msg=msg) , 404

my_memo_app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}</dt>
<dd>{{ field(**kwargs)| safe }}</dd>
{% if field.errors %}
<ul style="color: red;">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endmacro %}

my_memo_app/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>メモアプリ</title>
</head>

<body>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.logout') }}">ログアウト</a>
    {% endif %}
    {% block content %}{% endblock %}
</body>

</html>

my_memo_app/templates/create.html
{% extends "base.html" %}

{% block content %}
<h1>新しいメモを作成</h1>
<form method="post" action="{{ url_for('create') }}">
    <label for="title">タイトル</label>
    <input type="text" name="title" id="title" required>
    <br><br>
    <label for="content">内容</label>
    <textarea name="content" id="content" cols="50" rows="5" required></textarea>
    <br><br>
    <input type="submit" value="作成">
</form>

<a href="{{ url_for('index') }}">戻る</a>
{% endblock %}

my_memo_app/templates/memo/create_form.html
{% extends "base.html" %}

{% block content %}
<h1>新しいメモを作成</h1>
{% from "_formhelpers.html" import render_field %}
<form method="POST" action="{{ url_for('memo.create') }}" novalidate>
    {{ form.hidden_tag() }}
    {{ render_field(form.title) }}
    {{ render_field(form.content, rows=5, cols=50) }}
    {{ form.submit }}
</form>

<a href="{{ url_for('memo.index') }}">戻る</a>
{% endblock %}

my_memo_app/templates/memo/index.html
{% extends "base.html" %}

{% block content %}
<h1>メモ一覧</h1>
{% if memos == [] %}
<p>メモは登録されていません</p>
{% else %}
<ul>
    {% for memo in memos %}
    <li>{{ memo.title }} -
        <a href="{{ url_for('memo.update', memo_id=memo.id) }}">編集</a> |
        <a href="{{ url_for('memo.delete', memo_id=memo.id) }}">削除</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<!-- ▼▼▼▼▼ flashメッセージ ▼▼▼▼▼ -->
{% for message in get_flashed_messages() %}
<div style="color: blue;">
    {{ message }}
</div>
{% endfor %}
<!-- ▲▲▲▲▲ flashメッセージ ▲▲▲▲▲ -->
<a href="{{ url_for('memo.create') }}">新しいメモを作成</a>
{% endblock %}

my_memo_app/templates/memo/update_form.html
{% extends "base.html" %}

{% block content %}
<h1>メモを編集</h1>
{% from "_formhelpers.html" import render_field %}
<form method="post" action="{{ url_for('memo.update', memo_id=edit_id) }}" novalidate>
    {{ form.hidden_tag() }}
    {{ render_field(form.title) }}
    {{ render_field(form.content, rows=5, cols=50) }}
    {{ form.submit }}
</form>

<a href="{{ url_for('memo.index') }}">戻る</a>
{% endblock %}

my_memo_app/templates/update.html
{% extends "base.html" %}

{% block content %}
<h1>メモを編集</h1>
<form method="post" action="{{ url_for('update', memo_id=memo.id) }}">
    <label for="title">タイトル</label>
    <input type="text" name="title" id="title" value="{{ memo.title }}" required>
    <br><br>
    <label for="content">内容</label>
    <textarea name="content" id="content" cols="50" rows="5" required>{{ memo.content }}</textarea>
    <br><br>
    <input type="submit" value="更新">
</form>

<a href="{{ url_for('index') }}">戻る</a>
{% endblock %}