blueprint-sample/app.py
from flask import Flask, render_template

# ==================================================
# インスタンス生成
# ==================================================
app = Flask(__name__)

# ==================================================
# Blueprintの登録
# ==================================================
from application.one.views import one_bp
app.register_blueprint(one_bp)

from application.two.views import two_bp
app.register_blueprint(two_bp)

# ==================================================
# ルーティング
# ==================================================
@app.route('/')
def show_home():
    return render_template('home.html')

# ==================================================
# 実行
# ==================================================
if __name__ == '__main__':
    app.run()

blueprint-sample/application/one/views.py
from flask import Blueprint, render_template

# ==================================================
# Blueprintの定義
# ==================================================
one_bp = Blueprint('one_app', __name__, url_prefix='/one')

# ==================================================
# ルーティング
# ==================================================
@one_bp.route('/')
def show_template():
    return render_template('one/index.html')

blueprint-sample/application/two/views.py
from flask import Blueprint, render_template

# ==================================================
# Blueprintの定義
# ==================================================
two_bp = Blueprint('two_app', __name__, url_prefix='/two')

# ==================================================
# ルーティング
# ==================================================
@two_bp.route('/')
def show_template():
    return render_template('two/index.html')

blueprint-sample/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <title>Flask-Blueprint</title>
    {% block style %}{% endblock %}
</head>

<body>
    {% block content %} 内容 {% endblock %}
</body>

</html>

blueprint-sample/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Home</h1>
<a href="{{url_for('one_app.show_template')}}">アプリケーション：１</a>
<br>
<a href="{{url_for('two_app.show_template')}}">アプリケーション：２</a>
{% endblock %}

blueprint-sample/templates/one/index.html
{% extends "base.html" %}

{% block style %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style_one.css') }}">
{% endblock %}

{% block content %}
<h1>アプリケーション：１</h1>
<a href="{{url_for('show_home')}}">HOMEへ</a>
{% endblock %}

blueprint-sample/templates/two/index.html
{% extends "base.html" %}

{% block style %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style_two.css') }}">
{% endblock %}

{% block content %}
<h1>アプリケーション：２</h1>
<a href="{{url_for('show_home')}}">HOMEへ</a>
{% endblock %}